language: node_js
node_js:
- 10.12.0
env:
  global:
  - GIT_TAG=v$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - secure: oH5DNDBnz1wV1H+h3BADzU+RWRpXfrQSrFn8+ejRJGBi8I6zT2ri38pYAxTIV+HqyJYTmxe03sJuN3hyeO8GqrwXxY+B5O4BjpXGlv598P3mG2VPxqfjz27OCUQiv1edP+vjRkbGU4G/7RIFf7cyfLLvXizVgaHuHdBIYEdac8vEvlKPg3vygUtAzbL02JkIhEZbUCw3bBIacr9338Ki7WjXER8eN8nfeRNUm761YF1l/jt9/6eoQgXmmB2qO09FxklCH8nG84N4nxExyI4RVcDnEAg3eZU6NhaYuLEkV0dZvIsu2T5+yMOsvZMLEbqf7B8Ezuv648uTgl3kyTTiiMIIUZyL4jdZNrsiopX+Vgjx/dgpGVjtNmF25nLu0sBbyhnDDAa1L+LGQQxEwAA52Hi/+0wz4wGA+VC4rrx6GNRXDAoinfY1plq7nwBl3iAYddZfAzLj2ncH7/MfdIFvZcwCGjAgHsbhzOQFyGna+6mMZXbLHOn/r3nlZPbz7VpsvvMgbF8CU0Xd5mD/MWk8Gn7aaVS6c0J49YZn+09uXIP2rIay9ZPDdqrwhFPk9fglgFoB5pd8R4c2RGXQ4B7D6mg1HEKjnztcM3RPPGg+rWKNA8WmN+ThHF6GsVAWtUyYlvslS2HqrTCGRN0SXWLjs70HeZglcVIqIhp66PIhrvc=
sudo: required
dist: trusty
services:
- docker
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker pull postgres:10.4
- sudo service postgresql stop
- bash scripts/update_version.sh
- cat package.json
install:
- npm ci
script:
- npm run coverage
deploy:
  matrix:
  - provider: script
    on:
      type: push
    script: bash scripts/tag.sh
  - provider: npm
    skip_cleanup: true
    on:
      type: push
    email:
      secure: Z2KMmc2t/5tynj/heED4kav1krkOZ5ni25dQY6Fn3Vrd9WCN3P2Jbb7PPp/wX1rpiTJmGNRrABJNWaXCHYNxXubXnkV996Q4W26jET6NuId24SMWXrIxwk2TOks1NRVoGw+zDsEHDNscQk5HAzYOrWkTi0mKhtJcqnzuNH5qz0Qt6stnpdhLAvxtb3JKPVkVT4SyQ2K7D/LljWd5CMwCRX2EqGcbQinjzu0AFi285Wj316uMGy72YIev38UouP2eg/4iboJ8GAal0hgG5W22EnpwmuIZtEugpqWSk2G7t5Shaf7paCDwo4L11EbJoWffwByIT91Y7EtowlaKwyV6AWlvk/Nunq/jPDUpjwlv/pnyaNk41fY2/XIPtLSWbZ9RCVzS/L4nlSMChXEAL0OWoY7Rh1HCIeEevUIq/+WLLwukEzvRPLM4PRXWONYN9zPk3LhZXZzNWjyCuhhbrgqOdicFe3wsiykq7MTiQdAQ68rlIPIMgPnm8wxCJLU/3dDTeY9JnIb6/RUNbSSJgsqxjtIho28zBRTlrlySLNik3OqlK0gEpQ8wuZn50/fUwh5iGhRfv8Qx0L2h4Kel8/wM8ILT4AGXHfzcLURo8O7RQlWbB4I5JBFiyp97zE+GBiletwsVopwL3/qRcRS7WqVtpwd4dgM5We4tznTytsXlfio=
    api_key:
      secure: kZAGOc4ZXR/4XynduDKrGBJH4cQyNA642q6sNeC3kC59yWmWyTx8USuRvLokt1mi4h9FKXiy5cmA5JdH2ZLuFXNEXIKlsfRVwsqzY29z43E7UW2K/Mg++HZCsmKSJ/VOULvI2lyAvp1pJl3B2/gfrpvwgEs+bxBeE38CmjL0AIRHRg5dA+jTokF4Jc0kNp3QNosjKNjTce62tb1NCfmuNsfoKDhGWN9cFB12DyzQqqRfgzhfUkQUqZujCiOgCxaIiN7sVNB3OiKVh5Yfn/8Ug8biIg0gLwZbBj17uYfTjGK5bV2SxLrXdmUvAujsdcZJJRAmMb07fPqUsNs1QFGxg2jvJcc666Ax8/yXPBzBKsIHVElYwI7UF8h4Y56lsbvTZqQJ5j3EYbSGTAr8urbsPFbq6TMd4th9sERbJM/a/s2YYsXE9LvGbGs953cDjuOPXVXMXCOKibVe1hS7G/kqJ3A7rMalNbQb67a2oDjDC0WC94zljpyFllhxHqVXGEyRxSMx75LuR0EX/x9zSzOSeS5lpLjBOuldlJX1He9ozON58ZndKA98UepVtkIJ0Rd2k25DFtUS7wKTI6ZxE85blPfGEbM7Sdlrw7c0nVsilrLdj1EQRStM+5rbRAcXX8X/G1jKgaO/Udsa1wp9MCFf5kaKAaukB9EzRyg14+ePl1A=
