version: '3.6'
services:

  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_PASSWORD: iamaninsecurepassword
      POSTGRES_USER: beehive_user
      POSTGRES_DB: beehive
    ports:
      - 5432:5432

  beehive-service:
    build:
      context: ./build
      dockerfile: local/Dockerfile
    depends_on:
      - postgres
    environment:
      ENV: local
      PGPASSWORD: iamaninsecurepassword
      PGUSER: beehive_user
      PGDATABASE: beehive
      PGHOST: postgres
      BEEHIVE_ENABLE_EVENTS: "yes"
      PROTON_PACK_STREAM_URI: http://127.0.0.1:5000/streams/venkman
    ports:
      - 4022:4000
    command: "scripts/setup-and-startup.sh"
    volumes:
      - type: bind
        source: ./
        target: /app
